sudo: false
language: ruby
cache: bundler
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
rvm:
  - 2.3.1
gemfile:
  - Gemfile
  - Gemfile-rails5
matrix:
  allow_failures:
    - gemfile: Gemfile-rails5
deploy:
  provider: heroku
  api_key:
    secure: aHW/kPh1xVEUYwxRtgfL90oOVsLBlDl5z0fAV/zjhYkFVn9BJJSTODsJeR/+dZW9LQ4Bwtojz0V7tm47vk/99JfXiCxL2flP/WZCn5PmU0SHzrToFE5kctDqgLDCZcxVQO6KO3G63M8hj9QTfKfFrHCMEVLGjTv5SFHHqBQPRqk=
  app: secretsantacreator
  on:
    repo: emillon/secret-santa
  run: "rake db:migrate"
